### ISSUE TITLE
6월 22일 Implementation

### ISSUE THREAD

**Issue by JEONG-J** [JEONG-J/CodingTest#3]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

## ✏️ Description

Implementation 문제 해결

## To-Do List

- [x] [1343](https://www.acmicpc.net/problem/1343)
- [x] [1032](https://www.acmicpc.net/problem/2167)
- [x] [4659](https://www.acmicpc.net/problem/4659)

## ETC
반복학습하기
